const fs = require('fs');
const path = require('path');

function walk(dir, cb) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, cb);
    else cb(full);
  }
}

const root = path.resolve(__dirname, '..');
const findings = [];

const patterns = [
  { name: 'Absolute MEDIAWEB paths', re: /\/home\/[\w\-\/]*MEDIAWEB/ },
  { name: 'Absolute /var paths', re: /\/var\// },
  { name: 'IA generated markers', re: /AI-generated|IA-generated|generated by ai|assistant/i },
  { name: 'bak files', re: /\.bak$/i },
  { name: 'tsbuildinfo files', re: /\.tsbuildinfo$/i },
  { name: 'module-level client init', re: /new Stripe\(|createClient\(|supabaseClient|supabase.auth|supabase =/i },
  { name: 'console.*', re: /console\.(log|warn|error)\(/ },
  { name: 'absolute filesystem in strings', re: /\/[\w\-]+(\/\w+)+\/(MEDIAWEB|home)\//i }
];

walk(root, (file) => {
  if (!file.endsWith('.ts') && !file.endsWith('.tsx') && !file.endsWith('.js') && !file.endsWith('.jsx') && !file.endsWith('.json')) return;
  try {
    const content = fs.readFileSync(file, 'utf8');
    patterns.forEach(p => {
      if (p.re.test(content)) findings.push({ file: path.relative(root, file), name: p.name });
    });
  } catch (e) {}
});

console.log('Architecture check results:');
if (findings.length === 0) {
  console.log('  No common issues detected.');
  process.exit(0);
}

const byFile = {};
for (const f of findings) {
  byFile[f.file] = byFile[f.file] || new Set();
  byFile[f.file].add(f.name);
}

for (const file of Object.keys(byFile)) {
  console.log('\n- ' + file);
  for (const name of Array.from(byFile[file])) console.log('   * ' + name);
}

process.exit(0);
