export const IBERO_ORDER: Array<{ filename: string; text: string }> = [
  { filename: 'MARIA.jpg', text: "MARIA, A LOCAL CHEF FROM INNER ALENTEJO, SHE EVOKES IN HER ORIGINAL RECIPES INGREDIENTS AND TECHNIQUES THAT WERE POPULAR AMONG THE ROMANS THAT USED TO RULE THIS PART OF IBERIA" },
  { filename: 'TONI.jpg', text: "TONI, WHO USED TO WORK IN IT AND DECIDED TO APPROACH THE SHEPPERD'S LIFESTYLE, HE RECEIVES US IN HIS FARM AND TAKES US ON A SHORT HIKE WITH HIS GOATS, AND LET US TRY HOMEMADE CHEESE AND LOCAL TREATS." },
  { filename: 'VIDAL.jpg', text: "VIDAL, A DEHESA ESTATE OWNER, HAS BRED THE UNVALIABLE IBERICO AND RETINTO BREEDS FOR OVER 50 YEARS AND IS NOW RETIRED. HE WELCOMED US AND SHOWED US THE DEHESA'S MILLENIAL FARMING TECHNIQUES AND TREATED US TO A TRADITIONAL WESTERN SPANISH RICE MEAL (BLACK RICE)." },
  { filename: 'YOU', text: "YOU. YOU THAT ARE ABLE TO LET YOURSELF TRUST IN OUR HANDS TO GIVE YOU NEW LEARNINGS & EXPERIENCES, AS WELL AS DISCOVERING THE TREASURES THESE REGIONS HOLD." }
];
